// app/head.tsx
export default function Head() {
  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>HRP Consultancy</title>
      <meta name="description" content="Generated by create next app" />
      {/* any other tags you need */}
    </>
  );
}
